// <auto-generated />
using System;
using JobUpdatesAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobUpdatesAPI.Migrations
{
    [DbContext(typeof(JobUpdatesDbContext))]
    partial class JobUpdatesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobUpdatesAPI.Models.JobKeywordModel", b =>
                {
                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.Property<int>("KeywordId")
                        .HasColumnType("integer");

                    b.HasKey("JobId", "KeywordId");

                    b.HasIndex("KeywordId");

                    b.ToTable("JobKeywords");
                });

            modelBuilder.Entity("JobUpdatesAPI.Models.JobModel", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("JobId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxSalaryExpectation")
                        .HasColumnType("integer");

                    b.Property<int>("MinSalaryExpectation")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StatedSalaryExpectation")
                        .HasColumnType("integer");

                    b.HasKey("JobId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("JobUpdatesAPI.Models.JobStatusModel", b =>
                {
                    b.Property<short>("JobStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("JobStatusId"));

                    b.Property<int?>("JobUpdateId")
                        .HasColumnType("integer");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("JobStatusId");

                    b.HasIndex("JobUpdateId");

                    b.ToTable("JobStatuses");

                    b.HasData(
                        new
                        {
                            JobStatusId = (short)1,
                            StatusName = "N/A"
                        },
                        new
                        {
                            JobStatusId = (short)2,
                            StatusName = "Applied"
                        },
                        new
                        {
                            JobStatusId = (short)3,
                            StatusName = "Rejection"
                        },
                        new
                        {
                            JobStatusId = (short)4,
                            StatusName = "Holding CV"
                        },
                        new
                        {
                            JobStatusId = (short)5,
                            StatusName = "Awaiting Response"
                        },
                        new
                        {
                            JobStatusId = (short)6,
                            StatusName = "Scheduled Phone Call"
                        },
                        new
                        {
                            JobStatusId = (short)7,
                            StatusName = "Screening/ Pre-Interview"
                        },
                        new
                        {
                            JobStatusId = (short)8,
                            StatusName = "Interview"
                        },
                        new
                        {
                            JobStatusId = (short)9,
                            StatusName = "Offer"
                        });
                });

            modelBuilder.Entity("JobUpdatesAPI.Models.JobUpdateModel", b =>
                {
                    b.Property<int>("JobUpdateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("JobUpdateId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.Property<short>("JobStatusId")
                        .HasColumnType("smallint");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("JobUpdateId");

                    b.HasIndex("JobId");

                    b.HasIndex("JobStatusId");

                    b.ToTable("JobUpdates");
                });

            modelBuilder.Entity("JobUpdatesAPI.Models.KeywordModel", b =>
                {
                    b.Property<int>("KeywordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KeywordId"));

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("KeywordId");

                    b.ToTable("KeywordModel");
                });

            modelBuilder.Entity("JobUpdatesAPI.Models.JobKeywordModel", b =>
                {
                    b.HasOne("JobUpdatesAPI.Models.JobModel", "Job")
                        .WithMany("JobKeywords")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobUpdatesAPI.Models.KeywordModel", "Keyword")
                        .WithMany("JobKeywords")
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Keyword");
                });

            modelBuilder.Entity("JobUpdatesAPI.Models.JobStatusModel", b =>
                {
                    b.HasOne("JobUpdatesAPI.Models.JobUpdateModel", "JobUpdate")
                        .WithMany()
                        .HasForeignKey("JobUpdateId");

                    b.Navigation("JobUpdate");
                });

            modelBuilder.Entity("JobUpdatesAPI.Models.JobUpdateModel", b =>
                {
                    b.HasOne("JobUpdatesAPI.Models.JobModel", "Job")
                        .WithMany("JobUpdates")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobUpdatesAPI.Models.JobStatusModel", "Status")
                        .WithMany("JobUpdates")
                        .HasForeignKey("JobStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("JobUpdatesAPI.Models.JobModel", b =>
                {
                    b.Navigation("JobKeywords");

                    b.Navigation("JobUpdates");
                });

            modelBuilder.Entity("JobUpdatesAPI.Models.JobStatusModel", b =>
                {
                    b.Navigation("JobUpdates");
                });

            modelBuilder.Entity("JobUpdatesAPI.Models.KeywordModel", b =>
                {
                    b.Navigation("JobKeywords");
                });
#pragma warning restore 612, 618
        }
    }
}
